# SPDX-FileCopyrightText: 2024-present American Society Of Cinematographers
# SPDX-License-Identifier: Apache-2.0
# GenerateSchemaHeader.cmake
#
# Scans FDL_SCHEMA_DIR for v*/ascfdl.schema.json files and generates
# a C++ header with the schemas embedded as compile-time string literals.
#
# Input variables:
#   FDL_SCHEMA_DIR  - path to the schema directory (contains v0.1/, v2.0.1/, etc.)
#   FDL_SCHEMA_OUT  - output header file path
#
# The generated header provides:
#   fdl::detail::SchemaEntry  - struct with version + embedded JSON
#   fdl::detail::SCHEMA_REGISTRY[] - sorted array of all schemas
#   fdl::detail::SCHEMA_REGISTRY_SIZE - count

file(GLOB schema_dirs "${FDL_SCHEMA_DIR}/v*")
list(SORT schema_dirs)

# Parse version components from directory name (e.g. "v2.0.1" -> 2, 0, 1)
set(entries "")
set(var_decls "")
set(entry_count 0)

foreach(dir ${schema_dirs})
    set(schema_file "${dir}/ascfdl.schema.json")
    if(NOT EXISTS "${schema_file}")
        continue()
    endif()

    get_filename_component(dirname "${dir}" NAME)
    # Strip leading 'v'
    string(SUBSTRING "${dirname}" 1 -1 ver_str)

    # Split on '.'
    string(REPLACE "." ";" ver_parts "${ver_str}")
    list(LENGTH ver_parts num_parts)

    list(GET ver_parts 0 ver_major)
    list(GET ver_parts 1 ver_minor)
    if(num_parts GREATER 2)
        list(GET ver_parts 2 ver_patch)
    else()
        set(ver_patch -1)
    endif()

    # Read the schema file content
    file(READ "${schema_file}" schema_content)

    # Create a C++ variable name: SCHEMA_V2_0_1
    string(REPLACE "." "_" var_suffix "${ver_str}")
    set(var_name "SCHEMA_V${var_suffix}")

    # Accumulate variable declaration with raw string literal
    string(APPEND var_decls "inline constexpr const char* ${var_name} = R\"FDL_SCHEMA(\n${schema_content})FDL_SCHEMA\";\n\n")

    # Accumulate registry entry
    string(APPEND entries "    {${ver_major}, ${ver_minor}, ${ver_patch}, ${var_name}},\n")
    math(EXPR entry_count "${entry_count} + 1")
endforeach()

# Generate the header
file(WRITE "${FDL_SCHEMA_OUT}" "\
// AUTO-GENERATED by cmake/GenerateSchemaHeader.cmake — DO NOT EDIT
// Source: ${FDL_SCHEMA_DIR}
#ifndef FDL_SCHEMA_DATA_H
#define FDL_SCHEMA_DATA_H

#include <cstddef>

namespace fdl::detail {

struct SchemaEntry {
    int major;
    int minor;
    int patch;  // -1 if no patch version
    const char* data;
};

${var_decls}\
inline constexpr SchemaEntry SCHEMA_REGISTRY[] = {
${entries}\
};

inline constexpr size_t SCHEMA_REGISTRY_SIZE = ${entry_count};

} // namespace fdl::detail

#endif // FDL_SCHEMA_DATA_H
")

message(STATUS "Generated schema header with ${entry_count} schema versions -> ${FDL_SCHEMA_OUT}")
