# generated by datamodel-codegen:
#   filename:  ascfdl.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel, model_validator


class VersionModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    major: Literal[2]
    minor: Literal[0]


class FileSequenceModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    value: str
    idx: Annotated[str, Field(max_length=1, min_length=1)]
    min: Annotated[int, Field(ge=0)]
    max: Annotated[int, Field(ge=0)]


class ClipIDModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    clip_name: str
    file: str | None = None
    sequence: FileSequenceModel | None = None


class FitSource(Enum):
    framing_decision_dimensions = "framing_decision.dimensions"
    framing_decision_protection_dimensions = "framing_decision.protection_dimensions"
    canvas_dimensions = "canvas.dimensions"
    canvas_effective_dimensions = "canvas.effective_dimensions"


class FitMethod(Enum):
    width = "width"
    height = "height"
    fit_all = "fit_all"
    fill = "fill"


class AlignmentMethodVertical(Enum):
    top = "top"
    center = "center"
    bottom = "bottom"


class AlignmentMethodHorizontal(Enum):
    left = "left"
    center = "center"
    right = "right"


class PreserveFromSourceCanvas(Enum):
    framing_decision_dimensions = "framing_decision.dimensions"
    framing_decision_protection_dimensions = "framing_decision.protection_dimensions"
    canvas_dimensions = "canvas.dimensions"
    canvas_effective_dimensions = "canvas.effective_dimensions"


class Even(Enum):
    whole = "whole"
    even = "even"


class Mode(Enum):
    up = "up"
    down = "down"
    round = "round"


class RoundModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    even: Even
    mode: Mode


class FdlId(RootModel[str]):
    root: Annotated[str, Field(max_length=32, min_length=1, pattern="^[A-Za-z0-9_]+$")]


class FdlIdFramingDecision(RootModel[str]):
    root: Annotated[str, Field(max_length=65, min_length=3, pattern="^[A-Za-z0-9_]+-[A-Za-z0-9_]+$")]


class DimensionsIntModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    width: Annotated[int, Field(gt=0)]
    height: Annotated[int, Field(gt=0)]


class DimensionsFloatModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    width: Annotated[float, Field(gt=0.0)]
    height: Annotated[float, Field(gt=0.0)]


class PointFloatModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    x: Annotated[float, Field(ge=0.0)]
    y: Annotated[float, Field(ge=0.0)]


class FramingIntentModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    label: str | None = None
    id: FdlId
    aspect_ratio: DimensionsIntModel
    protection: Annotated[float | None, Field(ge=0.0)] = 0


class FramingDecisionModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    label: str | None = None
    id: FdlIdFramingDecision
    framing_intent_id: FdlId
    dimensions: DimensionsFloatModel
    anchor_point: PointFloatModel
    protection_dimensions: DimensionsFloatModel | None = None
    protection_anchor_point: PointFloatModel | None = None


class CanvasModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    label: str | None = None
    id: FdlId
    source_canvas_id: FdlId
    dimensions: DimensionsIntModel
    effective_dimensions: DimensionsIntModel | None = None
    effective_anchor_point: PointFloatModel | None = None
    photosite_dimensions: DimensionsIntModel | None = None
    physical_dimensions: DimensionsFloatModel | None = None
    anamorphic_squeeze: Annotated[float | None, Field(gt=0.0)] = 1.0
    framing_decisions: list[FramingDecisionModel] | None = None


class ContextModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    label: str | None = None
    context_creator: str | None = None
    clip_id: ClipIDModel | None = None
    canvases: list[CanvasModel] | None = None


class CanvasTemplateModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    label: str | None = None
    id: FdlId
    target_dimensions: DimensionsIntModel
    target_anamorphic_squeeze: Annotated[float, Field(gt=0.0)]
    fit_source: FitSource
    fit_method: FitMethod
    alignment_method_vertical: AlignmentMethodVertical | None = "center"
    alignment_method_horizontal: AlignmentMethodHorizontal | None = "center"
    preserve_from_source_canvas: PreserveFromSourceCanvas | None = None
    maximum_dimensions: DimensionsIntModel | None = None
    pad_to_maximum: bool | None = False
    round: RoundModel | None = None


class FramingDecisionList(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    uuid: UUID
    version: VersionModel
    fdl_creator: str | None = None
    default_framing_intent: FdlId | None = None
    framing_intents: list[FramingIntentModel] | None = None
    contexts: list[ContextModel] | None = None
    canvas_templates: list[CanvasTemplateModel] | None = None

    @model_validator(mode="after")
    def _validate_fdl_semantics(self) -> FramingDecisionList:
        """Run C-core schema + semantic validation on top of Pydantic validation."""
        from fdl import FDL

        json_bytes = self.model_dump_json(by_alias=True, exclude_none=True).encode("utf-8")
        doc = FDL.parse(json_bytes)
        doc.validate()
        return self
